apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-digest-updater-account
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-digest-updater
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
rules:
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  verbs:
  - list
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-digest-updater-binding
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-digest-updater
subjects:
- kind: ServiceAccount
  name: image-digest-updater-account
  namespace: default
