apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: {{ .Values.global.ci.namespace }}
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
type: kubernetes.io/generic
data:
  # We use index because of the dash in github-token :/
  token: {{ (index .Values.global.ci.secrets "github-token").token }}
