apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: github-status-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting ci/resources"
    kapp.k14s.io/update-strategy: "always-replace"
spec:
  taskRef:
    name: github-status
