apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: pipeline-run-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting ci/resources"
    kapp.k14s.io/update-strategy: "always-replace"
spec:
  pipelineRef:
    name: deploy-with-cue-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: repository-{{ .Values.global.ci.uid }}
