{{ if (or (eq .Values.trigger.event "all") (eq .Values.trigger.event .Values.global.ci.event)) }}
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: {{ .Values.name }}-repository-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  type: git
  params:
  - name: revision
    value: {{ .Values.global.ci.repository.revision }}
  - name: url
    value: {{ .Values.global.ci.repository.url }}
---

apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: {{ .Values.name }}-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting ci/resources"
    kapp.k14s.io/update-strategy: "always-replace"
spec:
  taskRef:
    name: {{ .Values.name }}
  resources:
    - name: source
      resourceRef:
        name: repository-{{ .Values.global.ci.uid }}
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: {{ .Values.name }}
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  inputs:
    resources:
      - name: source
        type: git
  steps:
{{- with .Values.steps }}
{{ toYaml . | indent 4 }}
{{- end }}
{{ end }}
