apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: deploy-with-cue
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
    kapp.k14s.io/update-strategy: "always-replace"
spec:
  inputs:
    resources:
      - name: source
        type: git
  steps:
    - name: generate-ci-config
      image: nixery.dev/shell/bash
      command: ["bash"]
      args:
        - "-c"
        - |
          set -e
          echo "# Generate ci.cue file"
          echo "package {{ .Values.cuePackage }}" > /workspace/source/{{ .Values.cuePath }}/ci.cue
          echo '_ci revision : "$(inputs.resources.source.revision)"' >> /workspace/source/{{ .Values.cuePath }}/ci.cue
          echo '_ci namespace : "{{ .Values.global.ci.namespace }}"' >> /workspace/source/{{ .Values.cuePath }}/ci.cue
          echo '_ci repository branch : "{{ .Values.global.ci.repository.branch }}"' >> /workspace/source/{{ .Values.cuePath }}/ci.cue
    - name: generate-config
      # Cue is not available in the channel used by nixery atm
      image: lewo/cue@sha256:b1d132d4eb0f4f6b9695346db9d43da81676ae3d8ecb5526dd11525d0d3f422b
      workingDir: /workspace/source/{{ .Values.cuePath }}
      command: ["bash"]
      args:
        - -c
        - |
          echo "# ci.cue"
          cat /workspace/source/{{ .Values.cuePath }}/ci.cue
          echo "# ---"
          cue export -p {{ .Values.cuePackage }} > /workspace/config.yaml
    - name: deploy
      image: nixery.dev/shell/kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-n"
        - {{ .Values.global.ci.namespace }}
        - "-f"
        - /workspace/config.yaml
